### ISSUE TITLE
OpenSesame should be disabled when opening a remote experiment

### ISSUE THREAD

**Issue by smathot** [dschreij/opensesame-extension-osf#3]
When you open an experiment from the OSF, you are immediately asked where you want to save your local version. However, once you've done that, it may take a while before the experiment has actually been downloaded and opened. In the meanwhile, you can keep working with OpenSesame. But this doesn't make sense, because everything you do will be discarded when the new experiment is opened.

A simple solution would be to disable the OpenSesame GUI until the experiment has been downloaded and opened.

**Comment by dschreij** [comment]
Good point. We need to make sure that the GUI becomes active again when the user for instance cancels the operation or it fails for some other reasons, but that should be possible by using the right callbacks

**Comment by dschreij** [comment]
This is implemented now using a modal dialog showing "Opening Experiment"
